### PR TITLE
Bump runtime to 42 and update to 1.6.1

### PR DESCRIPTION
**Pull request by bbhtt**
@bcedu, please review. Thanks!

### CODE REVIEW

**Comment by bbhtt** [comment]
bot, build

**Comment by bbhtt** [comment]
> Started [test build 103826](https://buildbot.flathub.org/#/builders/32/builds/103826)

The filename on the patch changed, I updated the patch.

**Comment by bbhtt** [comment]
bot, build

**Comment by bbhtt** [comment]
> Build [103848 failed](https://buildbot.flathub.org/#/builders/32/builds/103848)

aarch64 failed on uploading the build so restarting

bot, build

**Comment by bbhtt** [comment]
> Queued test build for com.github.bcedu.valasimplehttpserver.

Restarted this one by mistake instead of another one :/

**Comment by hfiguiere** [comment]
build fail because of Vala. tl;dr it broke.

**Comment by bbhtt** [comment]
> Build [103872 failed](https://buildbot.flathub.org/#/builders/32/builds/103872)

Faliure (for future reference):

```
HEAD is now at 3e7c976 Bumpt to v1.6.1
FB: Running: git rev-parse --verify --quiet 1.6.1:.gitmodules
Applying patch eos-theme.patch
FB: Running: patch -p1 -i /srv/buildbot/worker/build-x86_64/build/eos-theme.patch
patching file src/Application.vala
FB: Running 'flatpak build --die-with-parent --env=FLATPAK_BUILDER_BUILDDIR=/run/build/VServer --nofilesystem=host:reset --filesystem=/srv/buildbot/worker/build-x86_64/build/.flatpak-builder/build/VServer-1 --bind-mount=/run/build/VServer=/srv/buildbot/worker/build-x86_64/build/.flatpak-builder/build/VServer-1 --build-dir=/run/build/VServer/_flatpak_build --bind-mount=/run/ccache=/srv/buildbot/worker/build-x86_64/build/.flatpak-builder/ccache --unshare=network --env=SOURCE_DATE_EPOCH=1659869747 '--env=CFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer ' '--env=CXXFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer ' '--env=LDFLAGS=-L/app/lib -Wl,-z,relro,-z,now -Wl,--as-needed ' --env=CCACHE_DIR=/run/ccache/disabled --env=PATH=/app/bin:/usr/bin --env=LD_LIBRARY_PATH=/app/lib --env=PKG_CONFIG_PATH=/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig --env=FLATPAK_BUILDER_N_JOBS=48 /srv/buildbot/worker/build-x86_64/build/.flatpak-builder/rofiles/rofiles-ubqJ88 meson --prefix=/app .. -Dlibunity=false -Dubuntu-bionic-patched-vte=false' on host
The Meson build system
Version: 0.59.4
Source dir: /run/build/VServer
Build dir: /run/build/VServer/_flatpak_build
Build type: native build
WARNING: Unknown options: "libunity, ubuntu-bionic-patched-vte"
The value of new options can be set with:
meson setup <builddir> --reconfigure -Dnew_option=new_value ...
Project name: com.github.bcedu.valasimplehttpserver
Project version: 0.1.0
C compiler for the host machine: ccache cc (gcc 11.3.0 "cc (GCC) 11.3.0")
C linker for the host machine: cc ld.bfd 2.37
Vala compiler for the host machine: valac (valac 0.48.14)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.8.0)
Program glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Found pkg-config: /usr/bin/pkg-config (1.8.0)
Run-time dependency gobject-2.0 found: YES 2.72.3
Run-time dependency glib-2.0 found: YES 2.72.3
Run-time dependency gtk+-3.0 found: YES 3.24.34
Run-time dependency granite found: YES 5.5.0
Run-time dependency libhandy-1 found: YES 1.6.3
Run-time dependency gee-0.8 found: YES 0.20.3
Run-time dependency libqrencode found: YES 4.1.1
Library posix found: YES
Run-time dependency libsoup-3.0 found: YES 3.0.7
Found CMake: /usr/bin/cmake (3.23.2)
WARNING: CMake Toolchain: Failed to determine CMake compilers state
Run-time dependency unity found: NO (tried pkgconfig and cmake)
Run-time dependency appindicator3-0.1 found: NO (tried pkgconfig and cmake)
Program desktop-file-validate found: YES (/usr/bin/desktop-file-validate)
Program appstream-util found: YES (/usr/bin/appstream-util)
Program glib-compile-schemas found: YES (/usr/bin/glib-compile-schemas)
Program meson/post_install.py found: YES (/usr/bin/python3 /run/build/VServer/meson/post_install.py)
Build targets in project: 8
Found ninja-1.11.0 at /usr/bin/ninja
FB: host_command_exited_cb 1973690 0
]2;flatpak-builder: Installing VServerFB: Running 'flatpak build --die-with-parent --env=FLATPAK_BUILDER_BUILDDIR=/run/build/VServer --nofilesystem=host:reset --filesystem=/srv/buildbot/worker/build-x86_64/build/.flatpak-builder/build/VServer-1 --bind-mount=/run/build/VServer=/srv/buildbot/worker/build-x86_64/build/.flatpak-builder/build/VServer-1 --build-dir=/run/build/VServer/_flatpak_build --bind-mount=/run/ccache=/srv/buildbot/worker/build-x86_64/build/.flatpak-builder/ccache --unshare=network --env=SOURCE_DATE_EPOCH=1659869747 '--env=CFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer ' '--env=CXXFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer ' '--env=LDFLAGS=-L/app/lib -Wl,-z,relro,-z,now -Wl,--as-needed ' --env=CCACHE_DIR=/run/ccache/disabled --env=PATH=/app/bin:/usr/bin --env=LD_LIBRARY_PATH=/app/lib --env=PKG_CONFIG_PATH=/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig --env=FLATPAK_BUILDER_N_JOBS=48 /srv/buildbot/worker/build-x86_64/build/.flatpak-builder/rofiles/rofiles-ubqJ88 ninja -j48 -l96' on host
[1/21] Generating as-resources_h with a custom command
[2/21] Generating as-resources_c with a custom command
[3/21] Compiling C object src/com.github.bcedu.valasimplehttpserver.p/meson-generated_.._.._as-resources.c.o
[4/21] Generating com.github.bcedu.valasimplehttpserver.desktop_data_merge with a custom command
[5/21] Generating com.github.bcedu.valasimplehttpserver.appdata.xml_data_merge with a custom command
[6/21] Compiling Vala source ../src/configs/Constants.vala ../src/widgets/HeaderBar.vala ../src/views/AppView.vala ../src/views/InitialView.vala ../src/views/SharingView.vala ../src/views/ErrorView.vala ../src/views/ViewConf.vala ../src/controllers/ViewController.vala ../src/controllers/AppController.vala ../src/Application.vala ../src/Window.vala ../src/simpleHTTPserver.vala ../src/handlers/styles_handler.vala ../src/Main.vala
FAILED: src/com.github.bcedu.valasimplehttpserver.p/configs/Constants.c src/com.github.bcedu.valasimplehttpserver.p/widgets/HeaderBar.c src/com.github.bcedu.valasimplehttpserver.p/views/AppView.c src/com.github.bcedu.valasimplehttpserver.p/views/InitialView.c src/com.github.bcedu.valasimplehttpserver.p/views/SharingView.c src/com.github.bcedu.valasimplehttpserver.p/views/ErrorView.c src/com.github.bcedu.valasimplehttpserver.p/views/ViewConf.c src/com.github.bcedu.valasimplehttpserver.p/controllers/ViewController.c src/com.github.bcedu.valasimplehttpserver.p/controllers/AppController.c src/com.github.bcedu.valasimplehttpserver.p/Application.c src/com.github.bcedu.valasimplehttpserver.p/Window.c src/com.github.bcedu.valasimplehttpserver.p/simpleHTTPserver.c src/com.github.bcedu.valasimplehttpserver.p/handlers/styles_handler.c src/com.github.bcedu.valasimplehttpserver.p/Main.c 
valac -C --debug --debug -D LIBSOUP30 --pkg libsoup-3.0 --pkg posix --pkg libqrencode --pkg gee-0.8 --pkg libhandy-1 --pkg granite --pkg gtk+-3.0 --pkg glib-2.0 --pkg gobject-2.0 --color=always --directory src/com.github.bcedu.valasimplehttpserver.p --basedir ../src --gresources=../data/resources/com.github.bcedu.valasimplehttpserver.gresource.xml --vapidir=/run/build/VServer/src/vapis ../src/configs/Constants.vala ../src/widgets/HeaderBar.vala ../src/views/AppView.vala ../src/views/InitialView.vala ../src/views/SharingView.vala ../src/views/ErrorView.vala ../src/views/ViewConf.vala ../src/controllers/ViewController.vala ../src/controllers/AppController.vala ../src/Application.vala ../src/Window.vala ../src/simpleHTTPserver.vala ../src/handlers/styles_handler.vala ../src/Main.vala
libsoup-3.0.vapi:29.59-29.66: error: `GLib.Uri' is not a type
		public virtual GLib.SList<string> get_protection_space (GLib.Uri source_uri);

[...]
```




> build fail because of Vala. tl;dr it broke.

They should specify/update the minimum version of vala required for the build somewhere because it is no longer `>=0.16`. The elementary SDK ships vala 0.48.14 which is too old. It compiled fine with vala 0.52, so I'll add the vala sdk extension.

**Comment by bbhtt** [comment]
> They should specify/update the minimum version of vala required for the build somewhere because it is no longer `>=0.16`. The elementary SDK ships vala 0.48.14 which is too old. It compiled fine with vala 0.52, so I'll add the vala sdk extension.

Actually I realised that GNOME SDK has 0.56 so the vala sdk extension is redundant, I just need to keep the prepend-path to tell it to use vala from the GNOME SDK.

**Comment by bbhtt** [comment]
> Build [103905 failed](https://buildbot.flathub.org/#/builders/32/builds/103905)

Appdata validation fails:

```
• style-invalid         : <release> description should be prose and not contain hyperlinks [<p>Redesigned web navigation:</p><ul><li>Show directories on top, then the regular files sorted by type and alphabet</li><li>Don't display hidden files</li><li>Custom icon for each file depending on it's type</li><li>Responsive layout</li><li>Display file size</li><li>Display file type</li><li>Display modifications date</li></ul><p>Special thanks to @amka (https://github.com/amka) for this incredible work!</p>]
```

**Pull request merged**
